# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "user1")
User.create(username: "user2")
User.create(username: "user3")
User.create(username: "user4")
User.create(username: "user5")
User.create(username: "user6")
User.create(username: "user7")
User.create(username: "user8")
User.create(username: "user9")
User.create(username: "user10")

Artwork.create(title: "user1", image_url: "user1", artist_id: 1)
Artwork.create(title: "user2", image_url: "user2", artist_id: 2)
Artwork.create(title: "user3", image_url: "user3", artist_id: 3)
Artwork.create(title: "user4", image_url: "user4", artist_id: 4)
Artwork.create(title: "user5", image_url: "user5", artist_id: 5)
Artwork.create(title: "user6", image_url: "user6", artist_id: 6)
Artwork.create(title: "user7", image_url: "user7", artist_id: 7)
Artwork.create(title: "2user1", image_url: "user1", artist_id: 1)

ArtworkShare.create(viewer_id: 1, artwork_id: 2)
ArtworkShare.create(viewer_id: 1, artwork_id: 3)
ArtworkShare.create(viewer_id: 1, artwork_id: 4)
ArtworkShare.create(viewer_id: 1, artwork_id: 5)
ArtworkShare.create(viewer_id: 1, artwork_id: 6)
ArtworkShare.create(viewer_id: 1, artwork_id: 7)
ArtworkShare.create(viewer_id: 2, artwork_id: 1)
ArtworkShare.create(viewer_id: 2, artwork_id: 3)
ArtworkShare.create(viewer_id: 2, artwork_id: 4)
ArtworkShare.create(viewer_id: 2, artwork_id: 5)
ArtworkShare.create(viewer_id: 2, artwork_id: 6)
ArtworkShare.create(viewer_id: 2, artwork_id: 7)
ArtworkShare.create(viewer_id: 2, artwork_id: 8)

Comment.create(body: "user 10 on artwork 8", author_id: 10, artwork_id: 8)
Comment.create(body: "user 10 on artwork 8", author_id: 10, artwork_id: 8)
Comment.create(body: "user 10 on artwork 8", author_id: 10, artwork_id: 8)
Comment.create(body: "user 10 on artwork 8", author_id: 10, artwork_id: 8)
Comment.create(body: "user 10 on artwork 8", author_id: 10, artwork_id: 8)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
Comment.create(body: "user 10 on artwork 5", author_id: 10, artwork_id: 5)
